laravel/app/routes.php
| 4 - Rotas para os Painéis Administrativos (4ROTPAI)
|
*/

// LOCAL
// $dominioRepresentantes = "jandaia.dev";
// $dominioCadernos = "cadernosjandaia";
// $dominioConcurso = "todentro";

// TESTE
// $dominioRepresentantes = "jandaia.test.10.68.204.118.xip.io";
// $dominioCadernos = "cadernosjandaia.test.10.68.204.118.xip.io";
// $dominioConcurso = "todentro.test.10.68.204.118.xip.io";

// PRODUÇÃO
$dominioRepresentantes = "jandaia.com";
$dominioCadernos = "desativado";
$dominioConcurso = "desativado";

/*
|--------------------------------------------------------------------------
| Rotas para o site : REPRESENTANTES (1ROTREP)
|--------------------------------------------------------------------------
| Rotas que integram o funcionamento do site principal 'Representantes'
| o 'Representantes' atua como o site principal
*/
Route::group(array(), function()
{
	/* Views estáticas adicionais
	Route::get('campanha', function(){
		return View::make('representantes.campanha');
	});
	Route::get('fabricacao', function(){
		return View::make('representantes.fabricacao');
	}); */
	Route::get('educacao', array('as' => 'landing-educacao', function() {
		return View::make('representantes2017.educacao');
	}));

	Route::get('/', array('as' => 'representantes.home', 'uses' => 'Representantes\HomeController@index'));
	// Route::post('cadastro', array('as' => 'representantes.cadastro', 'uses' => 'Representantes\HomeController@cadastro'));

	Route::get('onde-encontrar', array('as' => 'representantes.encontrar', 'uses' => 'Representantes\EncontrarController@index'));
	Route::get('onde-encontrar/online', array('as' => 'representantes.encontrar.online', 'uses' => 'Representantes\EncontrarController@online'));
	Route::get('onde-encontrar/buscar', array('as' => 'representantes.encontrar.buscar', 'uses' => 'Representantes\EncontrarController@buscar'));

	/* EMPRESA */
	Route::get('a-jandaia', [
		'as'   => 'representantes.jandaia.empresa',
		'uses' => 'Representantes\JandaiaController@index'
	]);
	Route::get('a-jandaia/certificacoes', [
		'as'   => 'representantes.jandaia.certificacoes',
		'uses' => 'Representantes\JandaiaController@certificacoes'
	]);
	Route::get('a-jandaia/sustentabilidade', [
		'as'   => 'representantes.jandaia.sustentabilidade',
		'uses' => 'Representantes\JandaiaController@sustentabilidade'
	]);
	Route::get('a-jandaia/lab', [
		'as'   => 'representantes.jandaia.lab',
		'uses' => 'Representantes\JandaiaController@lab'
	]);
	Route::get('a-jandaia/exportacao', [
		'as'   => 'representantes.jandaia.exportacao',
		'uses' => 'Representantes\JandaiaController@exportacao'
	]);


	/*
	Route::get('empresa', function(){ return Redirect::to('empresa/historico'); });
	Route::get('empresa/melhor-escolha', array('as' => 'representantes.empresa.escolha', 'uses' => 'Representantes\EmpresaController@escolha'));
	Route::get('empresa/historico', array('as' => 'representantes.empresa.historico', 'uses' => 'Representantes\EmpresaController@historico'));
	Route::get('empresa/sustentabilidade', array('as' => 'representantes.empresa.sustentabilidade', 'uses' => 'Representantes\EmpresaController@sustentabilidade'));
	Route::get('empresa/certificacoes', array('as' => 'representantes.empresa.certificacoes', 'uses' => 'Representantes\EmpresaController@certificacoes'));
	Route::get('empresa/qualidade-jandaia', array('as' => 'representantes.empresa.qualidade', 'uses' => 'Representantes\EmpresaController@qualidade'));
	Route::get('empresa/produtos-personalizados', array('as' => 'representantes.empresa.produtos', 'uses' => 'Representantes\EmpresaController@produtos'));
	Route::get('empresa/exportacao', array('as' => 'representantes.empresa.exportacao', 'uses' => 'Representantes\EmpresaController@exportacao'));
	Route::get('empresa/lab', array('as' => 'representantes.empresa.lab', 'uses' => 'Representantes\EmpresaController@lab'));

	Route::get('international', array('as' => 'representantes.international', 'uses' => 'Representantes\EmpresaController@international'));
	Route::post('international/enviar', array('as' => 'representantes.contato-international', 'uses' => 'Representantes\ContatoController@enviarInternacional'));*/

	Route::get('download/{arquivo?}', function($arquivo = false){

		if(!$arquivo)
			App::abort('404');
		else{

			$pathToFile = app_path().'/internal_files/arquivos/'.$arquivo;

			if(file_exists($pathToFile))
				return Response::download($pathToFile);
			else
				App::abort('404');
		}
	});

	/* PRODUTOS */
	Route::get('produtos/{tipo?}/{linha?}/{produto?}', array('as' => 'representantes.produtos', 'uses' => 'Representantes\ProdutosController@index'));

	/* BUSCA DE PRODUTOS */
	Route::any('busca', array('as' => 'representantes.busca', function(){

		$termo = Input::get('termo');

		if(!$termo){
			return Redirect::to('produtos');
		}else{

			$resultados = DB::table('produtos_linhas')
								->orderBy('produtos_linhas.titulo')
								->join('produtos', 'produtos_linhas.id', '=', 'produtos.produtos_linha_id')
								->where('produtos_linhas.titulo', 'like', "%$termo%")
								->orWhere('produtos.detalhes', 'like', "%$termo%")
								->orWhere('produtos.titulo', 'like', "%$termo%")
								->get();

			foreach($resultados as $k => $v){
				$this_linha = Linha::find($v->produtos_linha_id);
				$v->linha_slug = is_null($this_linha) ? '' : $this_linha->slug;
				$this_tipo = Tipo::find($v->produtos_tipo_id);
				$v->tipo_slug = is_null($this_tipo) ? '' : $this_tipo->slug;
			}

			if(count($resultados) == 0){

				return View::make('representantes.produtos.busca2017')->with('mensagem', "Nenhum resultado para o termo: <strong>$termo</strong>")
														 ->with('listaTipos', Tipo::orderBy('titulo')->get())
														 ->with('listaLinhas', Linha::orderBy('titulo')->get())
														 ->with('resultados', false)
														 ->with('termo', $termo)
														 ->with('css', 'produtos');

			}else{

				return View::make('representantes.produtos.busca2017')->with('mensagem', "Resultados para o termo: <strong>$termo</strong>")
														->with('listaTipos', Tipo::orderBy('titulo')->get())
														->with('listaLinhas', Linha::orderBy('titulo')->get())
														->with('resultados', $resultados)
														->with('termo', $termo)
														->with('css', 'produtos');
			}
		}
	}));


	/* REPRESENTANTES */
	Route::any('representantes/{estado?}', array('as' => 'representantes.representantes', 'uses' => 'Representantes\RepresentantesController@index'));

	/* NOVIDADES
	Route::get('novidades/{slug?}', array('as' => 'representantes.novidades', 'uses' => 'Representantes\NovidadesController@index')); */

	/* CONTATO */
	Route::get('contato', array('as' => 'representantes.contato', 'uses' => 'Representantes\ContatoController@index'));
	Route::post('contato', array('as' => 'representantes.contato.enviar', 'uses' => 'Representantes\ContatoController@enviar'));

	/*
	|--------------------------------------------------------------------------
	| Rotas do Painel de Administração
	|--------------------------------------------------------------------------|
	*/

	// Página Inicial do Painel
	// Se estiver logado mostra a view
	// Se não estiver redireciona para painel/login
	Route::get('painel', array('before' => 'auth', 'as' => 'representantes.painel.home', 'uses' => 'Representantes\Painel\HomeController@index'));

	// Página de Login
	Route::get('painel/login', array('as' => 'representantes.painel.login', 'uses' => 'Representantes\Painel\HomeController@login'));

	// Autenticação do Login (via POST)
	Route::post('painel/login',  array('as' => 'representantes.painel.auth', function(){

		$authvars = array(
			'username' => Input::get('username'),
			'password' => Input::get('password'),
			'user_painel_concurso' => '0'
		);
		if(Auth::attempt($authvars)){
			return Redirect::to('painel');
		}else{
			Session::flash('login_errors', true);
			return Redirect::to('painel/login');
		}
	}));

	// Ação de logout
	Route::get('painel/logout', array('as' => 'representantes.painel.off', function(){
		Auth::logout();
		return Redirect::to('painel');
	}));

	/* Ajax de ordenação de resultados do painel */
	Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Representantes\AjaxController@gravaOrdem'));

	/* Busca Assíncrona de cidades para /fornecedores DEPRECATED */
	Route::get('ajax/pegarCidades/{id}', function($id){
		return Response::json(Cidade::where('estado', '=', $id)->get());
	});
});


Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
	Route::get('institucional/texto', array('as' => 'painel.institucional.texto', 'uses' => 'Representantes\Painel\InstitucionalController@texto'));
	Route::put('institucional/updateTexto', array('as' => 'painel.institucional.updateTexto', 'uses' => 'Representantes\Painel\InstitucionalController@updateTexto'));

    Route::resource('usuarios', 'Representantes\Painel\UsuariosController');
    Route::resource('banners', 'Representantes\Painel\BannersController');
    Route::resource('chamadas', 'Representantes\Painel\ChamadasController');
    Route::resource('novidades', 'Representantes\Painel\NovidadesController');
    Route::resource('tipos', 'Representantes\Painel\TiposController');
    Route::resource('linhas', 'Representantes\Painel\LinhasController');
    Route::resource('produtos', 'Representantes\Painel\ProdutosController');
    Route::resource('representantes', 'Representantes\Painel\RepresentantesController');
	Route::resource('institucional', 'Representantes\Painel\InstitucionalController');
	Route::resource('certificacoes', 'Representantes\Painel\CertificacoesController');
	Route::resource('cadastros', 'Representantes\Painel\CadastrosController');
	Route::get('painel/cadastros/download', array('as' => 'painel.cadastros.download', 'uses' => 'Representantes\Painel\CadastrosController@download'));

	Route::resource('onde-encontrar', 'Representantes\Painel\EncontrarController');

laravel/app/controllers/concurso/painel/BaseAdminController.php
<?php

namespace Concurso\Painel;

use View;

class BaseAdminController extends \Controller {

	/**
	 * Setup the layout used by the controller.
	 *
	 * @return void
	 */
	protected function setupLayout()
	{
		if ( ! is_null($this->layout))
		{
			$this->layout = View::make($this->layout);
		}
	}

}

laravel/app/controllers/concurso/painel/HomeController.php
<?php

namespace Concurso\Painel;

use View;

class HomeController extends BaseAdminController {

	/*
	|--------------------------------------------------------------------------
	| Default Home Controller
	|--------------------------------------------------------------------------
	|
	| You may wish to use controllers instead of, or in addition to, Closure
	| based routes. That's great! Here is an example controller method to
	| get you started. To route to this controller, just add the route:
	|
	|	Route::get('/', 'HomeController@showWelcome');
	|
	*/
	 /**
     * The layout that should be used for responses.
     */
    protected $layout = 'templates.painel.concurso';

	public function index()
	{
		$data = array();
		$this->layout->content = View::make('concurso.painel.home', $data);
	}

	public function login()
	{
		return View::make('concurso.painel.login');
	}

}

laravel/app/controllers/concurso/painel/ParticipacoesController.php
<?php

namespace Concurso\Painel;

use View, ParticipacoesConcurso;

class ParticipacoesController extends BaseAdminController {

	/*
	|--------------------------------------------------------------------------
	| Default Home Controller
	|--------------------------------------------------------------------------
	|
	| You may wish to use controllers instead of, or in addition to, Closure
	| based routes. That's great! Here is an example controller method to
	| get you started. To route to this controller, just add the route:
	|
	|	Route::get('/', 'HomeController@showWelcome');
	|
	*/
	 /**
     * The layout that should be used for responses.
     */
    protected $layout = 'templates.painel.concurso';

	public function index($etapa = false)
	{
		if(!$etapa)
			$this->layout->content = View::make('concurso.painel.participacoes.index')->with('registros', ParticipacoesConcurso::orderBy('nome_completo')->get())->with('etapa', 0);
		else
			$this->layout->content = View::make('concurso.painel.participacoes.index')->with('registros', ParticipacoesConcurso::where('etapa', '=', $etapa)->orderBy('nome_completo')->get())->with('etapa', $etapa);
	}

	public function view($id = false)
	{
		if(!$id)
			return Redirect('painel/participacoes');
		else
			$this->layout->content = View::make('concurso.painel.participacoes.detalhe')->with('registro', ParticipacoesConcurso::find($id));
	}

}

laravel/app/controllers/concurso/painel/UsuariosController.php
<?php

// Namespace
namespace Concurso\Painel;

// Core
use View, Input, Hash, Session, Redirect;

// Models
use User;

class UsuariosController extends BaseAdminController {

	protected $layout = 'templates.painel.concurso';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('concurso.painel.usuarios.index')->with('usuarios', User::where('user_painel_concurso', '=', 1)->get());
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('concurso.painel.usuarios.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$usuario = new User;
		$usuario->email = Input::get('email');
		$usuario->username = Input::get('username');
		$usuario->password = Hash::make(Input::get('password'));
		$usuario->user_painel_concurso = 1;
		$usuario->save();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Usuário criado com sucesso.');

		return Redirect::route('painel.usuarios.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('concurso.painel.usuarios.edit')->with('usuario', User::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$usuario = User::find($id);
		$usuario->email = Input::get('email');
		$usuario->username = Input::get('username');
		if(Input::get('password'))
			$usuario->password = Hash::make(Input::get('password'));
		$usuario->save();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Usuário alterado com sucesso.');

		return Redirect::route('painel.usuarios.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$usuario = User::find($id);
		$usuario->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Usuário removido com sucesso.');

		return Redirect::route('painel.usuarios.index');
	}

}

laravel/app/controllers/consumidor/painel/BaseAdminController.php
<?php

namespace Consumidor\Painel;

class BaseAdminController extends \Controller {

	/**
	 * Setup the layout used by the controller.
	 *
	 * @return void
	 */
	protected function setupLayout()
	{
		if ( ! is_null($this->layout))
		{
			$this->layout = \View::make($this->layout);
		}
	}

}

laravel/app/controllers/consumidor/painel/BlogCategoriasController.php
<?php

// Namespace
namespace Consumidor\Painel;

// Core
use View, Input, Str, Session, Redirect, File;

// Models
use BlogCategoria;

// Libs
use Imagine;

class BlogCategoriasController extends BaseAdminController {

	protected $layout = 'templates.painel.consumidor';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('consumidor.painel.categorias.index')->with('categorias', BlogCategoria::orderBy('id')->paginate(10));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('consumidor.painel.categorias.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$categoria = new BlogCategoria;

		$categoria->titulo = Input::get('titulo');
		$categoria->save();

		$categoria->slug = Str::slug($categoria->id.'_'.$categoria->titulo);
		$categoria->save();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Categoria criada com sucesso.');

		return Redirect::route('painel.categorias.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('consumidor.painel.categorias.edit')->with('categoria', BlogCategoria::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$categoria = BlogCategoria::find($id);

		$categoria->titulo = Input::get('titulo');
		$categoria->save();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Categoria alterada com sucesso.');

		return Redirect::route('painel.categorias.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$categoria = BlogCategoria::find($id);
		$categoria->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Categoria removida com sucesso.');

		return Redirect::route('painel.categorias.index');
	}

}

laravel/app/views/templates/painel/consumidor.blade.php
<!DOCTYPE html>
<html lang="pt-BR">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Painel Administrativo - Jandaia Cadernos</title>

	<meta name="robots" content="noindex, nofollow" />
	<meta name="author" content="Trupe Design" />
	<meta name="copyright" content="2013 Trupe Design" />
	<meta name="viewport" content="width=device-width,initial-scale=1">

	<base href="{{ url() }}/">
	<script> var BASE = "{{ url() }}/"</script>

<?= Assets::CSS(array(
	'painel/css/global',
	'jquery-theme-lightness/jquery-ui-1.8.20.custom',
  'fancybox/fancybox'))
?>

<?= Assets::JS(array(
	'libs/modernizr-2.0.6.min',
	'libs/jquery-1.8.0.min',
	'plugins/tinymce/tiny_mce',
	'libs/jquery-ui-1.10.1.custom.min',
	'plugins/jquery.ui.datepicker-pt-BR',
	'plugins/jquery.mtz.monthpicker',
	'plugins/jquery.uploadify.min',
  'plugins/fancybox',
	'plugins/bootstrap',
  'plugins/bootbox.min',
	'scripts/painel'))
?>

</head>
	<body>

	<div class="navbar ">
  		<div class="navbar-inner">

      			<a href="{{ URL::route('consumidor.painel.home') }}" class="brand">Jandaia Cadernos</a>

      			<ul class="nav">

        			<li @if(Route::currentRouteName() == 'painel.home') class='active' @endif><a href="{{ URL::route('consumidor.painel.home') }}">Início</a></li>

              <li @if(strpos(Route::currentRouteName(), 'painel.banners') !== FALSE) class='active' @endif><a href="{{ URL::route('painel.banners.index') }}">Banners</a></li>
              
              <li class="dropdown @if(strpos(Route::currentRouteName(), 'painel.blog') !== FALSE || strpos(Route::currentRouteName(), 'painel.categorias') !== FALSE)active@endif">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="{{ URL::route('painel.blog.index') }}">Posts</a></li>
                    <li><a href="{{ URL::route('painel.categorias.index') }}">Categorias</a></li>
                  </ul>
              </li>
              
              @if(Auth::user()->id == 7)
                <li class="dropdown @if(strpos(Route::currentRouteName(), 'painel.encontrar') !== FALSE) active @endif">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Onde Encontrar <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="{{ URL::route('painel.encontrar.index') }}">Lojas Físicas</a></li>
                    <li><a href="{{ URL::route('painel.encontraronline.index') }}">Lojas Virtuais</a></li>
                  </ul>
                </li>
              @endif

              <li class="dropdown @if(strpos(Route::currentRouteName(), 'painel.usuarios') !== FALSE)active@endif">
          				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Sistema <b class="caret"></b></a>
          				<ul class="dropdown-menu">
            				<li><a href="{{ URL::route('painel.usuarios.index') }}">Usuários</a></li>
            				<li><a href="{{ URL::route('consumidor.painel.off') }}">Logout</a></li>
          				</ul>
        			</li>

      			</ul>
  		</div>
	</div>

		@yield('conteudo')

		<div id="footer">
    		<hr>
    		<div class="inner">
      			<div class="container">
        			<p class="right">
          				<a href="#">Voltar ao topo</a>
        			</p>
        			<p>
          				&copy; <a href="http://www.trupe.net" target="_blank">Criação de Sites</a> : <a href="http://www.trupe.net" target="_blank">Trupe Agência Criativa</a>
        			</p>
      			</div>
    		</div>
  		</div>

	</body>
</html>

laravel/app/views/templates/painel/representantes.blade.php
<!DOCTYPE html>
<html lang="pt-BR">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Painel Administrativo - Jandaia Representantes</title>

	<meta name="robots" content="noindex, nofollow" />
	<meta name="author" content="Trupe Design" />
	<meta name="copyright" content="2013 Trupe Design" />
	<meta name="viewport" content="width=device-width,initial-scale=1">

	<base href="{{ url() }}/">
	<script> var BASE = "{{ url() }}"</script>

<?= Assets::CSS(array(
	'painel/css/global',
	'jquery-theme-lightness/jquery-ui-1.8.20.custom',
  'fancybox/fancybox'))
?>

<?= Assets::JS(array(
	'libs/modernizr-2.0.6.min',
	'libs/jquery-1.8.0.min',
	'plugins/tinymce/tiny_mce',
	'libs/jquery-ui-1.10.1.custom.min',
	'plugins/jquery.ui.datepicker-pt-BR',
	'plugins/jquery.mtz.monthpicker',
  'plugins/fancybox',
	'plugins/jquery.uploadify.min',
	'plugins/bootstrap',
  'plugins/bootbox.min',
	'scripts/painel'))
?>

</head>
	<body>

	<div class="navbar ">
  		<div class="navbar-inner">

      			<a href="{{ URL::route('representantes.painel.home') }}" class="brand">Jandaia Representantes</a>

      			<ul class="nav">

        			<li @if(Route::currentRouteName() == 'painel.home') class='active' @endif><a href="{{ URL::route('representantes.painel.home') }}">Início</a></li>

              <li @if(strpos(Route::currentRouteName(), 'painel.banners') !== FALSE) class='active' @endif><a href="{{ URL::route('painel.banners.index') }}">Banners</a></li>

              <li @if(strpos(Route::currentRouteName(), 'painel.chamadas') !== FALSE) class='active' @endif><a href="{{ URL::route('painel.chamadas.index') }}">Chamadas</a></li>

              <li @if(strpos(Route::currentRouteName(), 'painel.institucional') !== FALSE || strpos(Route::currentRouteName(), 'painel.certificacoes') !== FALSE) class='active' @endif><a href="{{ URL::route('painel.institucional.index') }}">Institucional</a></li>

              {{--<li @if(strpos(Route::currentRouteName(), 'painel.novidades') !== FALSE) class='active' @endif><a href="{{ URL::route('painel.novidades.index') }}">Novidades</a></li>--}}

              <li @if(strpos(Route::currentRouteName(), 'painel.representantes') !== FALSE) class='active' @endif><a href="{{ URL::route('painel.representantes.index') }}">Representantes</a></li>

              @if(Auth::user()->id == 7)
                <li class="dropdown @if(strpos(Route::currentRouteName(), 'painel.onde-encontrar') !== FALSE) active @endif">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Onde Encontrar <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="{{ URL::route('painel.onde-encontrar.index') }}">Lojas Físicas</a></li>
                    <li><a href="{{ URL::route('painel.onde-encontrar-online.index') }}">Lojas Virtuais</a></li>
                  </ul>
                </li>
              @endif

              @if(strpos(Route::currentRouteName(), 'painel.tipos') !== FALSE)
                <li class="dropdown active">
              @elseif(strpos(Route::currentRouteName(), 'painel.linhas') !== FALSE)
                <li class="dropdown active">
              @elseif(strpos(Route::currentRouteName(), 'painel.produtos') !== FALSE)
                <li class="dropdown active">
              @else
                <li class="dropdown">
              @endif
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Produtos <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="{{ URL::route('painel.linhas.index') }}">Linhas</a></li>
                    <li><a href="{{ URL::route('painel.produtos.index') }}">Produtos</a></li>
                  </ul>
              </li>

              <li @if(strpos(Route::currentRouteName(), 'painel.cadastros') !== FALSE) class='active' @endif><a href="{{ URL::route('painel.cadastros.index') }}">Cadastros</a></li>

        			<li class="dropdown @if(strpos(Route::currentRouteName(), 'painel.usuarios') !== FALSE)active@endif">
          				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Sistema <b class="caret"></b></a>
          				<ul class="dropdown-menu">
            				<li><a href="{{ URL::route('painel.usuarios.index') }}">Usuários</a></li>
            				<li><a href="{{ URL::route('representantes.painel.off') }}">Logout</a></li>
          				</ul>
        			</li>

      			</ul>
  		</div>
	</div>

		@yield('conteudo')

		<div id="footer">
    		<hr>
    		<div class="inner">
      			<div class="container">
        			<p class="right">
          				<a href="#">Voltar ao topo</a>
        			</p>
        			<p>
          				&copy; <a href="http://www.trupe.net" target="_blank">Criação de Sites</a> : <a href="http://www.trupe.net" target="_blank">Trupe Agência Criativa</a>
        			</p>
      			</div>
    		</div>
  		</div>

	</body>
</html>